[2025-02-22T23:43:57.769-0500] {processor.py:186} INFO - Started process (PID=26819) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-22T23:43:57.770-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-22T23:43:57.773-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:43:57.773-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-22T23:43:57.785-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:43:57.782-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:43:57.785-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-22T23:43:57.816-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.063 seconds
[2025-02-22T23:48:36.064-0500] {processor.py:186} INFO - Started process (PID=27459) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-22T23:48:36.067-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-22T23:48:36.093-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:48:36.092-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-22T23:48:36.176-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:48:36.154-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:48:36.177-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-22T23:48:36.281-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.267 seconds
[2025-02-22T23:49:42.867-0500] {processor.py:186} INFO - Started process (PID=27922) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-22T23:49:42.869-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-22T23:49:42.872-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:49:42.871-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-22T23:49:42.880-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:49:42.879-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:49:42.881-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-22T23:49:42.920-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.061 seconds
[2025-02-22T23:50:40.549-0500] {processor.py:186} INFO - Started process (PID=28367) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-22T23:50:40.551-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-22T23:50:40.554-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:50:40.553-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-22T23:50:40.564-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:50:40.563-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:50:40.565-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-22T23:50:40.599-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.059 seconds
[2025-02-22T23:51:39.660-0500] {processor.py:186} INFO - Started process (PID=28758) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-22T23:51:39.662-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-22T23:51:39.664-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:51:39.664-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-22T23:51:39.673-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:51:39.672-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:51:39.673-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-22T23:51:39.713-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.061 seconds
[2025-02-22T23:52:40.534-0500] {processor.py:186} INFO - Started process (PID=29215) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-22T23:52:40.536-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-22T23:52:40.538-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:52:40.538-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-22T23:52:40.550-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:52:40.547-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:52:40.551-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-22T23:52:40.582-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.057 seconds
[2025-02-22T23:54:13.676-0500] {processor.py:186} INFO - Started process (PID=29851) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-22T23:54:13.678-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-22T23:54:13.681-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:54:13.680-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-22T23:54:13.692-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:54:13.691-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:54:13.693-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-22T23:54:13.780-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.114 seconds
[2025-02-22T23:55:17.179-0500] {processor.py:186} INFO - Started process (PID=30316) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-22T23:55:17.187-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-22T23:55:17.200-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:55:17.190-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-22T23:55:17.241-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:55:17.233-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:55:17.242-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-22T23:55:17.304-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.150 seconds
[2025-02-22T23:58:27.132-0500] {processor.py:186} INFO - Started process (PID=30768) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-22T23:58:27.139-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-22T23:58:27.142-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:58:27.141-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-22T23:58:27.151-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:58:27.149-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:58:27.151-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-22T23:58:27.203-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.080 seconds
[2025-02-22T23:59:33.669-0500] {processor.py:186} INFO - Started process (PID=31251) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-22T23:59:33.673-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-22T23:59:33.678-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:59:33.677-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-22T23:59:33.697-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:59:33.695-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:59:33.698-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-22T23:59:33.732-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.077 seconds
[2025-02-23T00:00:56.726-0500] {processor.py:186} INFO - Started process (PID=31793) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:00:56.735-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T00:00:56.739-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:00:56.738-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:00:56.748-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:00:56.747-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:00:56.748-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:00:56.781-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.076 seconds
[2025-02-23T00:01:58.138-0500] {processor.py:186} INFO - Started process (PID=32185) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:01:58.141-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T00:01:58.144-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:01:58.143-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:01:58.152-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:01:58.151-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:01:58.152-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:01:58.184-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.054 seconds
[2025-02-23T00:11:35.938-0500] {processor.py:186} INFO - Started process (PID=34456) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:11:35.943-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T00:11:35.949-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:11:35.948-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:11:35.965-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:11:35.963-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:11:35.967-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:11:36.047-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.127 seconds
[2025-02-23T00:12:51.219-0500] {processor.py:186} INFO - Started process (PID=34570) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:12:51.220-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T00:12:51.224-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:12:51.223-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:12:51.233-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:12:51.231-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:12:51.233-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:12:51.260-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.051 seconds
[2025-02-23T00:13:49.887-0500] {processor.py:186} INFO - Started process (PID=34639) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:13:49.894-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T00:13:49.898-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:13:49.897-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:13:49.909-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:13:49.905-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:13:49.910-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:13:49.936-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.058 seconds
[2025-02-23T00:14:48.351-0500] {processor.py:186} INFO - Started process (PID=34714) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:14:48.353-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T00:14:48.357-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:14:48.356-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:14:48.369-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:14:48.368-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:14:48.370-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:14:48.406-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.064 seconds
[2025-02-23T00:15:57.652-0500] {processor.py:186} INFO - Started process (PID=34837) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:15:57.659-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T00:15:57.662-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:15:57.661-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:15:57.671-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:15:57.669-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:15:57.672-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:15:57.704-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.060 seconds
[2025-02-23T00:17:02.595-0500] {processor.py:186} INFO - Started process (PID=34918) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:17:02.599-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T00:17:02.602-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:17:02.602-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:17:02.611-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:17:02.610-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:17:02.611-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:17:02.642-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.056 seconds
[2025-02-23T00:18:02.183-0500] {processor.py:186} INFO - Started process (PID=34994) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:18:02.190-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T00:18:02.192-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:18:02.192-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:18:02.200-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:18:02.199-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:18:02.201-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:18:02.230-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.057 seconds
[2025-02-23T00:22:16.411-0500] {processor.py:186} INFO - Started process (PID=35201) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:22:16.413-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T00:22:16.417-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:22:16.416-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:22:16.426-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:22:16.425-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:22:16.426-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:22:16.459-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.056 seconds
[2025-02-23T00:23:21.364-0500] {processor.py:186} INFO - Started process (PID=35268) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:23:21.371-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T00:23:21.374-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:23:21.373-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:23:21.383-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:23:21.382-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:23:21.383-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:23:21.414-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.057 seconds
[2025-02-23T00:24:24.790-0500] {processor.py:186} INFO - Started process (PID=35346) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:24:24.792-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T00:24:24.794-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:24:24.794-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:24:24.803-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:24:24.802-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:24:24.803-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:24:24.839-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.057 seconds
[2025-02-23T00:25:23.870-0500] {processor.py:186} INFO - Started process (PID=35412) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:25:23.876-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T00:25:23.879-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:25:23.878-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:25:23.887-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:25:23.886-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:25:23.888-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:25:23.917-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.055 seconds
[2025-02-23T00:26:22.501-0500] {processor.py:186} INFO - Started process (PID=35488) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:26:22.508-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T00:26:22.511-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:26:22.510-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:26:22.520-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:26:22.519-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:26:22.520-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T00:26:22.554-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.061 seconds
[2025-02-23T02:31:51.277-0500] {processor.py:186} INFO - Started process (PID=76064) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:31:51.280-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T02:31:51.284-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:31:51.283-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:31:51.295-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:31:51.294-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:31:51.296-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:31:51.328-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.062 seconds
[2025-02-23T02:32:53.760-0500] {processor.py:186} INFO - Started process (PID=76463) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:32:53.763-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T02:32:53.770-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:32:53.770-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:32:53.785-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:32:53.783-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:32:53.786-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:32:53.825-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.075 seconds
[2025-02-23T02:34:07.865-0500] {processor.py:186} INFO - Started process (PID=76869) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:34:07.867-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T02:34:07.869-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:34:07.869-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:34:07.878-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:34:07.877-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:34:07.878-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:34:07.910-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.054 seconds
[2025-02-23T02:35:34.420-0500] {processor.py:186} INFO - Started process (PID=77211) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:35:34.447-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T02:35:34.450-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:35:34.450-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:35:34.473-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:35:34.471-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:35:34.474-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:35:34.513-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.126 seconds
[2025-02-23T02:43:18.974-0500] {processor.py:186} INFO - Started process (PID=79067) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:43:18.976-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T02:43:18.979-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:43:18.978-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:43:18.988-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:43:18.986-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:43:18.989-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:43:19.022-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.057 seconds
[2025-02-23T02:44:18.790-0500] {processor.py:186} INFO - Started process (PID=79269) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:44:18.792-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T02:44:18.796-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:44:18.795-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:44:18.805-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:44:18.804-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:44:18.805-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:44:18.836-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.058 seconds
[2025-02-23T02:45:22.718-0500] {processor.py:186} INFO - Started process (PID=79469) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:45:22.725-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T02:45:22.730-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:45:22.729-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:45:22.740-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:45:22.738-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:45:22.740-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:45:22.776-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.070 seconds
[2025-02-23T02:46:23.060-0500] {processor.py:186} INFO - Started process (PID=79689) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:46:23.062-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T02:46:23.065-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:46:23.064-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:46:23.076-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:46:23.074-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:46:23.076-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:46:23.111-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.062 seconds
[2025-02-23T02:47:33.761-0500] {processor.py:186} INFO - Started process (PID=79906) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:47:33.764-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T02:47:33.766-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:47:33.766-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:47:33.775-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:47:33.774-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:47:33.776-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:47:33.808-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.056 seconds
[2025-02-23T02:48:36.152-0500] {processor.py:186} INFO - Started process (PID=80097) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:48:36.159-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T02:48:36.162-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:48:36.162-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:48:36.171-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:48:36.169-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:48:36.171-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:48:36.202-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.058 seconds
[2025-02-23T02:49:38.892-0500] {processor.py:186} INFO - Started process (PID=80295) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:49:38.895-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T02:49:38.899-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:49:38.899-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:49:38.923-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:49:38.917-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:49:38.926-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:49:38.987-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.111 seconds
[2025-02-23T02:51:14.373-0500] {processor.py:186} INFO - Started process (PID=80561) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:51:14.377-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T02:51:14.389-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:51:14.388-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:51:14.402-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:51:14.401-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:51:14.403-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:51:14.469-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.117 seconds
[2025-02-23T02:52:30.078-0500] {processor.py:186} INFO - Started process (PID=80811) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:52:30.080-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T02:52:30.082-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:52:30.082-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:52:30.092-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:52:30.090-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:52:30.092-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:52:30.122-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.053 seconds
[2025-02-23T02:53:33.785-0500] {processor.py:186} INFO - Started process (PID=81003) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:53:33.788-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T02:53:33.790-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:53:33.790-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:53:33.798-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:53:33.797-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:53:33.799-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:53:33.830-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.054 seconds
[2025-02-23T02:54:36.092-0500] {processor.py:186} INFO - Started process (PID=81192) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:54:36.094-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T02:54:36.098-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:54:36.097-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:54:36.107-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:54:36.106-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:54:36.107-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:54:36.135-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.055 seconds
[2025-02-23T02:55:37.398-0500] {processor.py:186} INFO - Started process (PID=81381) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:55:37.404-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T02:55:37.407-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:55:37.407-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:55:37.417-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:55:37.416-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:55:37.418-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:55:37.452-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.065 seconds
[2025-02-23T02:56:40.947-0500] {processor.py:186} INFO - Started process (PID=81601) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:56:40.954-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T02:56:40.957-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:56:40.956-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:56:40.965-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:56:40.964-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:56:40.965-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:56:41.004-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.066 seconds
[2025-02-23T02:57:44.283-0500] {processor.py:186} INFO - Started process (PID=81821) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:57:44.288-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T02:57:44.291-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:57:44.291-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:57:44.300-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:57:44.299-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:57:44.300-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:57:44.335-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.069 seconds
[2025-02-23T02:58:48.399-0500] {processor.py:186} INFO - Started process (PID=82017) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:58:48.407-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T02:58:48.410-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:58:48.409-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:58:48.418-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:58:48.416-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:58:48.418-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:58:48.453-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.062 seconds
[2025-02-23T02:59:49.933-0500] {processor.py:186} INFO - Started process (PID=82209) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:59:49.940-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T02:59:49.942-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:59:49.942-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:59:49.952-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:59:49.951-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:59:49.953-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T02:59:49.986-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.063 seconds
[2025-02-23T03:00:57.425-0500] {processor.py:186} INFO - Started process (PID=82409) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:00:57.429-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T03:00:57.436-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:00:57.434-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:00:57.455-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:00:57.453-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:00:57.456-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:00:57.501-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.096 seconds
[2025-02-23T03:02:06.078-0500] {processor.py:186} INFO - Started process (PID=82670) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:02:06.079-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T03:02:06.083-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:02:06.083-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:02:06.093-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:02:06.092-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:02:06.093-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:02:06.125-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.058 seconds
[2025-02-23T03:03:27.168-0500] {processor.py:186} INFO - Started process (PID=83526) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:03:27.170-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T03:03:27.173-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:03:27.173-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:03:27.181-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:03:27.180-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:03:27.182-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:03:27.216-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.056 seconds
[2025-02-23T03:04:36.118-0500] {processor.py:186} INFO - Started process (PID=83737) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:04:36.120-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T03:04:36.123-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:04:36.122-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:04:36.132-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:04:36.131-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:04:36.133-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:04:36.169-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.063 seconds
[2025-02-23T03:05:40.568-0500] {processor.py:186} INFO - Started process (PID=83932) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:05:40.570-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T03:05:40.572-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:05:40.572-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:05:40.581-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:05:40.580-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:05:40.581-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:05:40.618-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.058 seconds
[2025-02-23T03:06:41.409-0500] {processor.py:186} INFO - Started process (PID=84149) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:06:41.411-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T03:06:41.414-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:06:41.413-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:06:41.422-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:06:41.421-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:06:41.423-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:06:41.452-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.052 seconds
[2025-02-23T03:07:40.875-0500] {processor.py:186} INFO - Started process (PID=84331) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:07:40.877-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T03:07:40.880-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:07:40.879-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:07:40.892-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:07:40.891-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:07:40.893-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:07:40.925-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.066 seconds
[2025-02-23T03:08:46.124-0500] {processor.py:186} INFO - Started process (PID=84530) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:08:46.131-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T03:08:46.134-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:08:46.134-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:08:46.143-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:08:46.142-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:08:46.144-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:08:46.174-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.058 seconds
[2025-02-23T03:09:50.001-0500] {processor.py:186} INFO - Started process (PID=84752) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:09:50.050-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T03:09:50.055-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:09:50.054-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:09:50.104-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:09:50.092-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:09:50.105-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:09:50.188-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.235 seconds
[2025-02-23T03:10:54.944-0500] {processor.py:186} INFO - Started process (PID=84953) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:10:54.946-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T03:10:54.949-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:10:54.949-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:10:54.963-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:10:54.962-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:10:54.964-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:10:54.994-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.061 seconds
[2025-02-23T03:11:58.594-0500] {processor.py:186} INFO - Started process (PID=85173) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:11:58.596-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T03:11:58.599-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:11:58.599-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:11:58.608-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:11:58.607-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:11:58.609-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:11:58.640-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.054 seconds
[2025-02-23T03:13:00.221-0500] {processor.py:186} INFO - Started process (PID=85367) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:13:00.223-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T03:13:00.228-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:13:00.227-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:13:00.242-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:13:00.240-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:13:00.242-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:13:00.273-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.064 seconds
[2025-02-23T03:14:11.376-0500] {processor.py:186} INFO - Started process (PID=85584) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:14:11.382-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T03:14:11.385-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:14:11.385-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:14:11.394-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:14:11.393-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:14:11.395-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:14:11.429-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.061 seconds
[2025-02-23T03:15:16.956-0500] {processor.py:186} INFO - Started process (PID=85844) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:15:16.963-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T03:15:16.966-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:15:16.966-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:15:16.975-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:15:16.974-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:15:16.975-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:15:17.009-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.063 seconds
[2025-02-23T03:16:19.261-0500] {processor.py:186} INFO - Started process (PID=86070) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:16:19.268-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py for tasks to queue
[2025-02-23T03:16:19.272-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:16:19.271-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:16:19.281-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:16:19.280-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py", line 42, in <module>
    def branch(task_id_to_return: str) -> str:
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:16:19.282-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py
[2025-02-23T03:16:19.312-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_nested_branch_dag.py took 0.060 seconds
