[2025-02-22T23:43:55.372-0500] {processor.py:186} INFO - Started process (PID=26817) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:43:55.373-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-22T23:43:55.377-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:43:55.377-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:43:55.395-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:43:55.389-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:43:55.396-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:43:55.440-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.079 seconds
[2025-02-22T23:48:33.583-0500] {processor.py:186} INFO - Started process (PID=27419) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:48:33.591-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-22T23:48:33.596-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:48:33.595-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:48:33.634-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:48:33.615-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:48:33.635-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:48:33.699-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.142 seconds
[2025-02-22T23:49:41.205-0500] {processor.py:186} INFO - Started process (PID=27920) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:49:41.207-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-22T23:49:41.210-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:49:41.209-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:49:41.221-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:49:41.219-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:49:41.221-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:49:41.252-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.056 seconds
[2025-02-22T23:50:39.746-0500] {processor.py:186} INFO - Started process (PID=28364) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:50:39.750-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-22T23:50:39.753-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:50:39.753-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:50:39.774-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:50:39.766-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:50:39.775-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:50:39.808-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.074 seconds
[2025-02-22T23:51:38.069-0500] {processor.py:186} INFO - Started process (PID=28736) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:51:38.071-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-22T23:51:38.074-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:51:38.073-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:51:38.087-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:51:38.085-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:51:38.087-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:51:38.119-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.058 seconds
[2025-02-22T23:52:38.107-0500] {processor.py:186} INFO - Started process (PID=29196) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:52:38.109-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-22T23:52:38.111-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:52:38.111-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:52:38.126-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:52:38.121-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:52:38.126-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:52:38.164-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.068 seconds
[2025-02-22T23:54:10.910-0500] {processor.py:186} INFO - Started process (PID=29846) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:54:10.915-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-22T23:54:10.921-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:54:10.920-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:54:10.950-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:54:10.938-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:54:10.951-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:54:11.020-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.125 seconds
[2025-02-22T23:55:14.547-0500] {processor.py:186} INFO - Started process (PID=30276) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:55:14.550-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-22T23:55:14.553-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:55:14.553-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:55:14.586-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:55:14.573-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:55:14.587-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:55:14.652-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.119 seconds
[2025-02-22T23:58:25.756-0500] {processor.py:186} INFO - Started process (PID=30750) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:58:25.764-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-22T23:58:25.767-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:58:25.766-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:58:25.780-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:58:25.778-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:58:25.781-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:58:25.824-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.076 seconds
[2025-02-22T23:59:31.223-0500] {processor.py:186} INFO - Started process (PID=31249) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:59:31.226-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-22T23:59:31.229-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:59:31.228-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:59:31.248-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:59:31.239-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:59:31.249-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:59:31.287-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.074 seconds
[2025-02-23T00:00:54.279-0500] {processor.py:186} INFO - Started process (PID=31754) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:00:54.281-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T00:00:54.284-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:00:54.284-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:00:54.297-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:00:54.295-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:00:54.297-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:00:54.328-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.057 seconds
[2025-02-23T00:01:55.798-0500] {processor.py:186} INFO - Started process (PID=32183) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:01:55.800-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T00:01:55.803-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:01:55.802-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:01:55.813-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:01:55.811-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:01:55.813-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:01:55.840-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.051 seconds
[2025-02-23T00:11:34.614-0500] {processor.py:186} INFO - Started process (PID=34452) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:11:34.621-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T00:11:34.625-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:11:34.624-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:11:34.644-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:11:34.637-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:11:34.645-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:11:34.690-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.084 seconds
[2025-02-23T00:12:48.789-0500] {processor.py:186} INFO - Started process (PID=34568) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:12:48.791-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T00:12:48.794-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:12:48.794-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:12:48.804-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:12:48.802-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:12:48.805-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:12:48.831-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.050 seconds
[2025-02-23T00:13:47.425-0500] {processor.py:186} INFO - Started process (PID=34635) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:13:47.431-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T00:13:47.435-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:13:47.434-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:13:47.444-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:13:47.442-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:13:47.444-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:13:47.474-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.058 seconds
[2025-02-23T00:14:45.788-0500] {processor.py:186} INFO - Started process (PID=34710) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:14:45.790-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T00:14:45.793-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:14:45.792-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:14:45.802-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:14:45.801-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:14:45.803-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:14:45.834-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.054 seconds
[2025-02-23T00:15:55.321-0500] {processor.py:186} INFO - Started process (PID=34835) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:15:55.323-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T00:15:55.326-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:15:55.325-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:15:55.336-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:15:55.334-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:15:55.336-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:15:55.367-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.054 seconds
[2025-02-23T00:17:00.268-0500] {processor.py:186} INFO - Started process (PID=34907) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:17:00.269-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T00:17:00.272-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:17:00.272-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:17:00.282-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:17:00.280-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:17:00.282-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:17:00.313-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.054 seconds
[2025-02-23T00:18:00.712-0500] {processor.py:186} INFO - Started process (PID=34985) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:18:00.720-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T00:18:00.724-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:18:00.723-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:18:00.734-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:18:00.732-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:18:00.734-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:18:00.770-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.067 seconds
[2025-02-23T00:22:14.346-0500] {processor.py:186} INFO - Started process (PID=35199) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:22:14.348-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T00:22:14.350-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:22:14.350-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:22:14.360-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:22:14.358-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:22:14.360-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:22:14.390-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.053 seconds
[2025-02-23T00:23:19.291-0500] {processor.py:186} INFO - Started process (PID=35266) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:23:19.299-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T00:23:19.302-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:23:19.302-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:23:19.315-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:23:19.312-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:23:19.315-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:23:19.348-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.065 seconds
[2025-02-23T00:24:22.330-0500] {processor.py:186} INFO - Started process (PID=35344) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:24:22.337-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T00:24:22.341-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:24:22.340-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:24:22.351-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:24:22.349-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:24:22.352-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:24:22.384-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.065 seconds
[2025-02-23T00:25:21.780-0500] {processor.py:186} INFO - Started process (PID=35410) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:25:21.786-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T00:25:21.789-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:25:21.788-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:25:21.798-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:25:21.797-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:25:21.799-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:25:21.830-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.059 seconds
[2025-02-23T00:26:21.020-0500] {processor.py:186} INFO - Started process (PID=35486) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:26:21.022-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T00:26:21.025-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:26:21.024-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:26:21.035-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:26:21.033-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:26:21.035-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:26:21.076-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.065 seconds
[2025-02-23T02:31:50.295-0500] {processor.py:186} INFO - Started process (PID=76060) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:31:50.303-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T02:31:50.305-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:31:50.305-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:31:50.315-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:31:50.313-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:31:50.316-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:31:50.349-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.063 seconds
[2025-02-23T02:32:52.710-0500] {processor.py:186} INFO - Started process (PID=76462) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:32:52.713-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T02:32:52.716-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:32:52.715-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:32:52.725-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:32:52.723-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:32:52.725-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:32:52.761-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.059 seconds
[2025-02-23T02:34:07.540-0500] {processor.py:186} INFO - Started process (PID=76868) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:34:07.547-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T02:34:07.550-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:34:07.549-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:34:07.559-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:34:07.558-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:34:07.560-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:34:07.594-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.064 seconds
[2025-02-23T02:35:34.133-0500] {processor.py:186} INFO - Started process (PID=77210) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:35:34.135-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T02:35:34.139-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:35:34.138-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:35:34.153-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:35:34.150-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:35:34.154-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:35:34.208-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.086 seconds
[2025-02-23T02:43:18.619-0500] {processor.py:186} INFO - Started process (PID=79066) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:43:18.620-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T02:43:18.624-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:43:18.623-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:43:18.634-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:43:18.632-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:43:18.634-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:43:18.664-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.054 seconds
[2025-02-23T02:44:17.610-0500] {processor.py:186} INFO - Started process (PID=79268) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:44:17.616-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T02:44:17.619-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:44:17.618-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:44:17.630-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:44:17.627-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:44:17.630-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:44:17.658-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.057 seconds
[2025-02-23T02:45:21.549-0500] {processor.py:186} INFO - Started process (PID=79462) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:45:21.552-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T02:45:21.555-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:45:21.554-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:45:21.570-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:45:21.567-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:45:21.572-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:45:21.606-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.069 seconds
[2025-02-23T02:46:22.294-0500] {processor.py:186} INFO - Started process (PID=79682) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:46:22.302-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T02:46:22.306-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:46:22.305-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:46:22.320-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:46:22.318-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:46:22.322-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:46:22.355-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.074 seconds
[2025-02-23T02:47:32.615-0500] {processor.py:186} INFO - Started process (PID=79899) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:47:32.617-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T02:47:32.620-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:47:32.619-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:47:32.634-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:47:32.632-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:47:32.635-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:47:32.676-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.078 seconds
[2025-02-23T02:48:34.975-0500] {processor.py:186} INFO - Started process (PID=80096) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:48:34.982-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T02:48:34.985-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:48:34.984-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:48:34.994-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:48:34.993-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:48:34.995-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:48:35.026-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.060 seconds
[2025-02-23T02:49:37.537-0500] {processor.py:186} INFO - Started process (PID=80288) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:49:37.540-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T02:49:37.547-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:49:37.546-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:49:37.560-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:49:37.558-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:49:37.561-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:49:37.655-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.129 seconds
[2025-02-23T02:51:13.144-0500] {processor.py:186} INFO - Started process (PID=80557) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:51:13.147-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T02:51:13.152-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:51:13.151-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:51:13.171-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:51:13.168-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:51:13.172-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:51:13.210-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.109 seconds
[2025-02-23T02:52:29.276-0500] {processor.py:186} INFO - Started process (PID=80804) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:52:29.278-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T02:52:29.281-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:52:29.280-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:52:29.292-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:52:29.289-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:52:29.293-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:52:29.325-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.058 seconds
[2025-02-23T02:53:32.614-0500] {processor.py:186} INFO - Started process (PID=80996) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:53:32.615-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T02:53:32.618-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:53:32.617-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:53:32.627-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:53:32.626-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:53:32.628-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:53:32.655-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.050 seconds
[2025-02-23T02:54:34.893-0500] {processor.py:186} INFO - Started process (PID=81191) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:54:34.900-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T02:54:34.904-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:54:34.903-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:54:34.915-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:54:34.912-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:54:34.915-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:54:34.955-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.071 seconds
[2025-02-23T02:55:36.227-0500] {processor.py:186} INFO - Started process (PID=81380) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:55:36.232-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T02:55:36.236-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:55:36.235-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:55:36.250-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:55:36.248-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:55:36.251-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:55:36.285-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.069 seconds
[2025-02-23T02:56:39.783-0500] {processor.py:186} INFO - Started process (PID=81600) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:56:39.785-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T02:56:39.789-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:56:39.788-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:56:39.800-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:56:39.797-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:56:39.800-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:56:39.832-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.057 seconds
[2025-02-23T02:57:43.154-0500] {processor.py:186} INFO - Started process (PID=81820) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:57:43.156-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T02:57:43.158-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:57:43.158-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:57:43.168-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:57:43.166-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:57:43.168-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:57:43.200-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.057 seconds
[2025-02-23T02:58:47.230-0500] {processor.py:186} INFO - Started process (PID=82016) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:58:47.232-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T02:58:47.236-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:58:47.236-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:58:47.246-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:58:47.244-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:58:47.247-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:58:47.279-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.059 seconds
[2025-02-23T02:59:49.563-0500] {processor.py:186} INFO - Started process (PID=82205) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:59:49.565-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T02:59:49.568-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:59:49.568-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:59:49.580-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:59:49.578-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:59:49.580-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:59:49.608-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.059 seconds
[2025-02-23T03:00:56.236-0500] {processor.py:186} INFO - Started process (PID=82402) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:00:56.238-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T03:00:56.242-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:00:56.241-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:00:56.259-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:00:56.256-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:00:56.260-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:00:56.301-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.079 seconds
[2025-02-23T03:02:05.710-0500] {processor.py:186} INFO - Started process (PID=82669) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:02:05.723-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T03:02:05.728-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:02:05.727-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:02:05.746-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:02:05.743-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:02:05.747-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:02:05.795-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.100 seconds
[2025-02-23T03:03:25.920-0500] {processor.py:186} INFO - Started process (PID=83523) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:03:25.922-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T03:03:25.926-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:03:25.925-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:03:25.939-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:03:25.937-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:03:25.940-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:03:26.004-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.097 seconds
[2025-02-23T03:04:35.565-0500] {processor.py:186} INFO - Started process (PID=83736) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:04:35.571-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T03:04:35.574-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:04:35.574-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:04:35.588-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:04:35.585-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:04:35.589-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:04:35.641-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.086 seconds
[2025-02-23T03:05:39.419-0500] {processor.py:186} INFO - Started process (PID=83931) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:05:39.421-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T03:05:39.424-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:05:39.423-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:05:39.433-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:05:39.432-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:05:39.434-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:05:39.465-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.054 seconds
[2025-02-23T03:06:40.206-0500] {processor.py:186} INFO - Started process (PID=84148) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:06:40.207-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T03:06:40.210-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:06:40.210-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:06:40.220-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:06:40.218-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:06:40.220-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:06:40.254-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.057 seconds
[2025-02-23T03:07:39.542-0500] {processor.py:186} INFO - Started process (PID=84327) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:07:39.548-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T03:07:39.554-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:07:39.552-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:07:39.566-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:07:39.563-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:07:39.566-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:07:39.648-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.119 seconds
[2025-02-23T03:08:44.956-0500] {processor.py:186} INFO - Started process (PID=84529) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:08:44.958-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T03:08:44.961-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:08:44.961-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:08:44.971-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:08:44.969-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:08:44.972-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:08:45.003-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.055 seconds
[2025-02-23T03:09:48.658-0500] {processor.py:186} INFO - Started process (PID=84751) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:09:48.663-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T03:09:48.674-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:09:48.674-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:09:48.698-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:09:48.692-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:09:48.699-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:09:48.755-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.118 seconds
[2025-02-23T03:10:54.150-0500] {processor.py:186} INFO - Started process (PID=84949) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:10:54.153-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T03:10:54.156-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:10:54.155-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:10:54.168-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:10:54.165-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:10:54.169-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:10:54.217-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.079 seconds
[2025-02-23T03:11:57.426-0500] {processor.py:186} INFO - Started process (PID=85172) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:11:57.432-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T03:11:57.436-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:11:57.436-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:11:57.446-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:11:57.444-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:11:57.447-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:11:57.478-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.061 seconds
[2025-02-23T03:12:59.943-0500] {processor.py:186} INFO - Started process (PID=85366) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:12:59.945-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T03:12:59.958-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:12:59.949-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:12:59.988-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:12:59.985-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:12:59.993-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:13:00.088-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.161 seconds
[2025-02-23T03:14:10.213-0500] {processor.py:186} INFO - Started process (PID=85581) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:14:10.215-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T03:14:10.218-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:14:10.217-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:14:10.230-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:14:10.228-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:14:10.231-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:14:10.258-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.060 seconds
[2025-02-23T03:15:15.799-0500] {processor.py:186} INFO - Started process (PID=85837) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:15:15.801-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T03:15:15.804-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:15:15.803-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:15:15.814-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:15:15.812-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:15:15.814-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:15:15.842-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.052 seconds
[2025-02-23T03:16:18.100-0500] {processor.py:186} INFO - Started process (PID=86056) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:16:18.102-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T03:16:18.105-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:16:18.104-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:16:18.115-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:16:18.114-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:16:18.116-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:16:18.149-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.059 seconds
[2025-02-23T03:17:18.149-0500] {processor.py:186} INFO - Started process (PID=86264) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:17:18.153-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T03:17:18.158-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:17:18.157-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:17:18.180-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:17:18.177-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:17:18.181-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:17:18.214-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.080 seconds
[2025-02-23T03:18:21.763-0500] {processor.py:186} INFO - Started process (PID=86510) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:18:21.765-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T03:18:21.768-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:18:21.767-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:18:21.780-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:18:21.778-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:18:21.781-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:18:21.815-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.065 seconds
[2025-02-23T03:19:24.937-0500] {processor.py:186} INFO - Started process (PID=86780) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:19:24.939-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T03:19:24.942-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:19:24.941-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:19:24.951-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:19:24.949-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:19:24.952-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:19:24.982-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.056 seconds
[2025-02-23T03:20:28.769-0500] {processor.py:186} INFO - Started process (PID=86979) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:20:28.776-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T03:20:28.779-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:20:28.778-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:20:28.789-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:20:28.787-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T03:20:28.789-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T03:20:28.822-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.061 seconds
