[2025-02-22T23:44:01.857-0500] {processor.py:186} INFO - Started process (PID=26845) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:44:01.859-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-22T23:44:01.863-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:44:01.862-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:44:01.868-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:44:01.867-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-22T23:44:01.868-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:44:01.868-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-22T23:44:01.868-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:44:01.880-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-02-22T23:48:40.006-0500] {processor.py:186} INFO - Started process (PID=27465) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:48:40.008-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-22T23:48:40.012-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:48:40.011-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:48:40.025-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:48:40.024-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-22T23:48:40.025-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:48:40.025-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-22T23:48:40.026-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:48:40.056-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-22T23:49:47.320-0500] {processor.py:186} INFO - Started process (PID=27982) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:49:47.322-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-22T23:49:47.325-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:49:47.324-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:49:47.330-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:49:47.329-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-22T23:49:47.330-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:49:47.330-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-22T23:49:47.331-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:49:47.343-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-02-22T23:50:45.164-0500] {processor.py:186} INFO - Started process (PID=28374) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:50:45.166-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-22T23:50:45.168-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:50:45.168-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:50:45.173-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:50:45.172-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-22T23:50:45.173-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:50:45.173-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-22T23:50:45.174-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:50:45.186-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-02-22T23:51:43.249-0500] {processor.py:186} INFO - Started process (PID=28764) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:51:43.251-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-22T23:51:43.254-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:51:43.253-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:51:43.260-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:51:43.260-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-22T23:51:43.261-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:51:43.261-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-22T23:51:43.261-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:51:43.274-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-02-22T23:52:44.326-0500] {processor.py:186} INFO - Started process (PID=29221) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:52:44.329-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-22T23:52:44.334-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:52:44.334-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:52:44.341-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:52:44.340-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-22T23:52:44.342-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:52:44.341-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-22T23:52:44.342-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:52:44.355-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2025-02-22T23:54:17.379-0500] {processor.py:186} INFO - Started process (PID=29874) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:54:17.381-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-22T23:54:17.385-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:54:17.384-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:54:17.392-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:54:17.392-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-22T23:54:17.393-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:54:17.393-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-22T23:54:17.393-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:54:17.407-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2025-02-22T23:57:28.056-0500] {processor.py:186} INFO - Started process (PID=30439) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:57:28.062-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-22T23:57:28.067-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:57:28.066-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:57:28.077-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:57:28.076-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-22T23:57:28.077-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:57:28.077-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-22T23:57:28.078-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:57:28.114-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.073 seconds
[2025-02-22T23:58:48.018-0500] {processor.py:186} INFO - Started process (PID=30935) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:58:48.020-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-22T23:58:48.025-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:58:48.023-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:58:48.035-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:58:48.034-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-22T23:58:48.035-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:58:48.035-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-22T23:58:48.035-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-22T23:58:48.054-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2025-02-23T00:00:01.682-0500] {processor.py:186} INFO - Started process (PID=31434) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:00:01.684-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T00:00:01.691-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:00:01.690-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:00:01.704-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:00:01.703-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T00:00:01.705-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:00:01.705-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T00:00:01.706-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:00:01.735-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-02-23T00:01:16.358-0500] {processor.py:186} INFO - Started process (PID=31908) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:01:16.360-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T00:01:16.363-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:01:16.362-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:01:16.368-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:01:16.367-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T00:01:16.368-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:01:16.368-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T00:01:16.368-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:01:16.381-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-02-23T00:11:40.657-0500] {processor.py:186} INFO - Started process (PID=34462) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:11:40.661-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T00:11:40.666-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:11:40.665-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:11:40.675-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:11:40.674-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T00:11:40.675-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:11:40.675-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T00:11:40.676-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:11:40.690-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.075 seconds
[2025-02-23T00:12:55.149-0500] {processor.py:186} INFO - Started process (PID=34574) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:12:55.151-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T00:12:55.156-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:12:55.155-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:12:55.160-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:12:55.160-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T00:12:55.160-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:12:55.160-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T00:12:55.161-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:12:55.175-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-02-23T00:13:53.855-0500] {processor.py:186} INFO - Started process (PID=34643) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:13:53.857-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T00:13:53.865-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:13:53.864-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:13:53.876-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:13:53.874-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T00:13:53.878-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:13:53.878-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T00:13:53.879-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:13:53.909-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-02-23T00:14:51.649-0500] {processor.py:186} INFO - Started process (PID=34718) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:14:51.654-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T00:14:51.660-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:14:51.659-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:14:51.668-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:14:51.667-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T00:14:51.670-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:14:51.668-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T00:14:51.670-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:14:51.691-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2025-02-23T00:16:01.667-0500] {processor.py:186} INFO - Started process (PID=34847) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:16:01.669-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T00:16:01.673-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:16:01.672-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:16:01.677-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:16:01.677-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T00:16:01.677-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:16:01.677-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T00:16:01.678-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:16:01.692-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2025-02-23T00:17:07.144-0500] {processor.py:186} INFO - Started process (PID=34922) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:17:07.151-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T00:17:07.154-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:17:07.154-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:17:07.159-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:17:07.158-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T00:17:07.159-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:17:07.159-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T00:17:07.159-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:17:07.172-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-02-23T00:18:06.175-0500] {processor.py:186} INFO - Started process (PID=34998) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:18:06.182-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T00:18:06.185-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:18:06.184-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:18:06.189-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:18:06.189-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T00:18:06.190-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:18:06.190-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T00:18:06.190-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:18:06.203-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-02-23T00:22:22.121-0500] {processor.py:186} INFO - Started process (PID=35205) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:22:22.123-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T00:22:22.126-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:22:22.125-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:22:22.131-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:22:22.130-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T00:22:22.131-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:22:22.131-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T00:22:22.132-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:22:22.147-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.052 seconds
[2025-02-23T00:23:25.643-0500] {processor.py:186} INFO - Started process (PID=35272) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:23:25.650-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T00:23:25.653-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:23:25.652-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:23:25.657-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:23:25.657-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T00:23:25.658-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:23:25.657-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T00:23:25.658-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:23:25.670-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-02-23T00:24:28.338-0500] {processor.py:186} INFO - Started process (PID=35350) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:24:28.339-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T00:24:28.343-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:24:28.342-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:24:28.348-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:24:28.347-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T00:24:28.348-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:24:28.348-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T00:24:28.349-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:24:28.363-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-02-23T00:25:27.872-0500] {processor.py:186} INFO - Started process (PID=35417) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:25:27.874-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T00:25:27.877-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:25:27.876-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:25:27.883-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:25:27.882-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T00:25:27.883-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:25:27.883-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T00:25:27.883-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:25:27.897-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-02-23T00:26:27.248-0500] {processor.py:186} INFO - Started process (PID=35492) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:26:27.250-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T00:26:27.253-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:26:27.252-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:26:27.257-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:26:27.257-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T00:26:27.258-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:26:27.258-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T00:26:27.258-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T00:26:27.271-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-02-23T02:31:54.886-0500] {processor.py:186} INFO - Started process (PID=76101) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:31:54.888-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T02:31:54.891-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:31:54.891-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:31:54.896-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:31:54.895-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T02:31:54.896-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:31:54.896-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T02:31:54.897-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:31:54.911-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2025-02-23T02:32:57.334-0500] {processor.py:186} INFO - Started process (PID=76472) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:32:57.339-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T02:32:57.343-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:32:57.342-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:32:57.347-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:32:57.347-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T02:32:57.348-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:32:57.347-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T02:32:57.348-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:32:57.364-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2025-02-23T02:34:11.511-0500] {processor.py:186} INFO - Started process (PID=76892) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:34:11.513-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T02:34:11.519-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:34:11.517-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:34:11.525-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:34:11.524-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T02:34:11.526-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:34:11.526-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T02:34:11.527-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:34:11.544-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-02-23T02:43:22.567-0500] {processor.py:186} INFO - Started process (PID=79082) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:43:22.569-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T02:43:22.572-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:43:22.571-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:43:22.577-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:43:22.576-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T02:43:22.578-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:43:22.577-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T02:43:22.578-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:43:22.593-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-02-23T02:44:21.821-0500] {processor.py:186} INFO - Started process (PID=79278) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:44:21.826-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T02:44:21.831-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:44:21.831-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:44:21.838-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:44:21.837-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T02:44:21.838-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:44:21.838-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T02:44:21.839-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:44:21.852-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.061 seconds
[2025-02-23T02:45:25.563-0500] {processor.py:186} INFO - Started process (PID=79478) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:45:25.595-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T02:45:25.601-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:45:25.600-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:45:25.608-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:45:25.608-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T02:45:25.609-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:45:25.608-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T02:45:25.609-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:45:25.625-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.096 seconds
[2025-02-23T02:46:26.907-0500] {processor.py:186} INFO - Started process (PID=79698) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:46:26.916-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T02:46:26.919-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:46:26.918-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:46:26.924-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:46:26.923-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T02:46:26.924-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:46:26.924-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T02:46:26.925-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:46:26.944-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2025-02-23T02:47:36.703-0500] {processor.py:186} INFO - Started process (PID=79915) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:47:36.708-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T02:47:36.720-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:47:36.719-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:47:36.736-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:47:36.735-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T02:47:36.737-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:47:36.737-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T02:47:36.738-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:47:36.800-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.144 seconds
[2025-02-23T02:48:39.749-0500] {processor.py:186} INFO - Started process (PID=80106) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:48:39.756-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T02:48:39.759-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:48:39.759-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:48:39.764-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:48:39.763-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T02:48:39.764-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:48:39.764-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T02:48:39.765-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:48:39.778-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-02-23T02:49:42.494-0500] {processor.py:186} INFO - Started process (PID=80304) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:49:42.536-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T02:49:42.541-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:49:42.540-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:49:42.558-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:49:42.557-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T02:49:42.559-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:49:42.558-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T02:49:42.559-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:49:42.622-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.161 seconds
[2025-02-23T02:51:18.338-0500] {processor.py:186} INFO - Started process (PID=80597) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:51:18.348-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T02:51:18.361-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:51:18.360-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:51:18.370-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:51:18.369-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T02:51:18.372-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:51:18.371-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T02:51:18.372-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:51:18.398-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.081 seconds
[2025-02-23T02:52:33.687-0500] {processor.py:186} INFO - Started process (PID=80820) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:52:33.694-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T02:52:33.697-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:52:33.696-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:52:33.701-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:52:33.701-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T02:52:33.702-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:52:33.702-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T02:52:33.702-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:52:33.716-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-02-23T02:53:37.413-0500] {processor.py:186} INFO - Started process (PID=81013) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:53:37.416-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T02:53:37.421-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:53:37.420-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:53:37.427-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:53:37.426-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T02:53:37.427-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:53:37.427-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T02:53:37.428-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:53:37.444-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.054 seconds
[2025-02-23T02:54:39.794-0500] {processor.py:186} INFO - Started process (PID=81203) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:54:39.801-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T02:54:39.805-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:54:39.805-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:54:39.810-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:54:39.809-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T02:54:39.811-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:54:39.810-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T02:54:39.812-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:54:39.829-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2025-02-23T02:55:41.079-0500] {processor.py:186} INFO - Started process (PID=81396) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:55:41.083-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T02:55:41.097-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:55:41.096-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:55:41.104-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:55:41.103-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T02:55:41.105-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:55:41.105-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T02:55:41.106-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:55:41.140-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.086 seconds
[2025-02-23T02:56:43.062-0500] {processor.py:186} INFO - Started process (PID=81610) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:56:43.064-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T02:56:43.067-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:56:43.066-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:56:43.071-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:56:43.071-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T02:56:43.072-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:56:43.072-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T02:56:43.072-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:56:43.086-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-02-23T02:57:46.936-0500] {processor.py:186} INFO - Started process (PID=81831) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:57:46.942-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T02:57:46.945-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:57:46.945-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:57:46.949-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:57:46.949-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T02:57:46.950-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:57:46.950-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T02:57:46.950-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:57:46.966-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2025-02-23T02:58:51.983-0500] {processor.py:186} INFO - Started process (PID=82026) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:58:51.985-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T02:58:51.988-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:58:51.987-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:58:51.992-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:58:51.991-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T02:58:51.992-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:58:51.992-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T02:58:51.993-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:58:52.005-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-02-23T02:59:53.578-0500] {processor.py:186} INFO - Started process (PID=82218) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:59:53.580-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T02:59:53.584-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:59:53.583-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:59:53.589-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:59:53.588-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T02:59:53.589-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:59:53.589-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T02:59:53.590-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T02:59:53.605-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-02-23T03:01:00.858-0500] {processor.py:186} INFO - Started process (PID=82435) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:01:00.865-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:01:00.869-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:01:00.868-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:01:00.873-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:01:00.873-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:01:00.874-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:01:00.873-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:01:00.874-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:01:00.888-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-02-23T03:02:09.743-0500] {processor.py:186} INFO - Started process (PID=82685) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:02:09.745-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:02:09.749-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:02:09.748-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:02:09.756-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:02:09.756-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:02:09.757-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:02:09.757-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:02:09.757-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:02:09.773-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2025-02-23T03:03:29.910-0500] {processor.py:186} INFO - Started process (PID=83535) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:03:29.913-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:03:29.917-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:03:29.916-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:03:29.922-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:03:29.922-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:03:29.923-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:03:29.923-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:03:29.923-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:03:29.938-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-02-23T03:04:39.628-0500] {processor.py:186} INFO - Started process (PID=83746) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:04:39.630-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:04:39.634-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:04:39.634-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:04:39.640-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:04:39.640-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:04:39.641-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:04:39.641-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:04:39.642-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:04:39.662-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2025-02-23T03:05:43.702-0500] {processor.py:186} INFO - Started process (PID=83941) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:05:43.704-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:05:43.707-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:05:43.706-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:05:43.711-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:05:43.710-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:05:43.711-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:05:43.711-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:05:43.712-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:05:43.725-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-02-23T03:06:44.206-0500] {processor.py:186} INFO - Started process (PID=84158) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:06:44.207-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:06:44.210-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:06:44.209-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:06:44.214-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:06:44.214-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:06:44.215-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:06:44.215-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:06:44.215-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:06:44.230-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-02-23T03:07:43.596-0500] {processor.py:186} INFO - Started process (PID=84337) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:07:43.598-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:07:43.601-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:07:43.600-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:07:43.607-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:07:43.606-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:07:43.607-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:07:43.607-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:07:43.608-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:07:43.622-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-02-23T03:08:49.126-0500] {processor.py:186} INFO - Started process (PID=84540) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:08:49.133-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:08:49.136-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:08:49.135-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:08:49.140-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:08:49.140-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:08:49.141-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:08:49.140-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:08:49.141-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:08:49.155-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-02-23T03:09:53.885-0500] {processor.py:186} INFO - Started process (PID=84761) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:09:53.889-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:09:53.894-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:09:53.893-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:09:53.910-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:09:53.909-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:09:53.911-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:09:53.911-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:09:53.912-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:09:53.944-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2025-02-23T03:10:58.391-0500] {processor.py:186} INFO - Started process (PID=84965) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:10:58.393-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:10:58.398-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:10:58.397-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:10:58.405-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:10:58.404-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:10:58.406-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:10:58.405-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:10:58.406-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:10:58.455-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2025-02-23T03:12:02.102-0500] {processor.py:186} INFO - Started process (PID=85195) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:12:02.109-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:12:02.112-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:12:02.112-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:12:02.116-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:12:02.116-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:12:02.117-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:12:02.117-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:12:02.118-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:12:02.131-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2025-02-23T03:13:03.950-0500] {processor.py:186} INFO - Started process (PID=85382) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:13:03.952-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:13:03.957-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:13:03.956-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:13:03.973-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:13:03.972-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:13:03.974-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:13:03.974-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:13:03.974-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:13:04.013-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.081 seconds
[2025-02-23T03:14:14.209-0500] {processor.py:186} INFO - Started process (PID=85593) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:14:14.211-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:14:14.214-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:14:14.214-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:14:14.219-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:14:14.218-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:14:14.219-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:14:14.219-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:14:14.220-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:14:14.233-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-02-23T03:15:19.805-0500] {processor.py:186} INFO - Started process (PID=85853) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:15:19.813-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:15:19.816-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:15:19.815-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:15:19.820-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:15:19.820-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:15:19.821-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:15:19.820-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:15:19.821-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:15:19.835-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2025-02-23T03:16:22.624-0500] {processor.py:186} INFO - Started process (PID=86085) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:16:22.632-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:16:22.635-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:16:22.634-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:16:22.640-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:16:22.639-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:16:22.640-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:16:22.640-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:16:22.641-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:16:22.654-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-02-23T03:17:22.165-0500] {processor.py:186} INFO - Started process (PID=86274) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:17:22.168-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:17:22.170-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:17:22.170-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:17:22.175-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:17:22.174-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:17:22.175-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:17:22.175-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:17:22.176-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:17:22.190-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-02-23T03:18:25.787-0500] {processor.py:186} INFO - Started process (PID=86520) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:18:25.789-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:18:25.792-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:18:25.791-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:18:25.796-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:18:25.796-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:18:25.797-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:18:25.797-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:18:25.797-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:18:25.813-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-02-23T03:19:28.918-0500] {processor.py:186} INFO - Started process (PID=86790) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:19:28.920-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:19:28.923-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:19:28.922-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:19:28.927-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:19:28.926-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:19:28.927-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:19:28.927-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:19:28.928-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:19:28.941-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-02-23T03:20:32.643-0500] {processor.py:186} INFO - Started process (PID=86997) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:20:32.645-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:20:32.648-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:20:32.648-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:20:32.653-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:20:32.652-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:20:32.653-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:20:32.653-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:20:32.654-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:20:32.667-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-02-23T03:21:33.596-0500] {processor.py:186} INFO - Started process (PID=87217) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:21:33.603-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:21:33.609-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:21:33.608-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:21:33.615-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:21:33.614-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:21:33.615-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:21:33.615-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:21:33.616-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:21:33.660-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.074 seconds
[2025-02-23T03:22:32.749-0500] {processor.py:186} INFO - Started process (PID=87432) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:22:32.751-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:22:32.754-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:22:32.754-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:22:32.759-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:22:32.758-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:22:32.759-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:22:32.759-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:22:32.759-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:22:32.773-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-02-23T03:23:39.013-0500] {processor.py:186} INFO - Started process (PID=87632) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:23:39.020-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:23:39.023-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:23:39.023-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:23:39.028-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:23:39.027-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:23:39.028-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:23:39.028-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:23:39.028-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:23:39.041-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2025-02-23T03:24:42.756-0500] {processor.py:186} INFO - Started process (PID=87832) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:24:42.758-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:24:42.761-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:24:42.760-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:24:42.765-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:24:42.765-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:24:42.766-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:24:42.766-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:24:42.766-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:24:42.780-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-02-23T03:25:47.332-0500] {processor.py:186} INFO - Started process (PID=88046) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:25:47.334-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:25:47.337-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:25:47.336-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:25:47.341-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:25:47.340-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:25:47.341-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:25:47.341-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:25:47.342-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:25:47.357-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-02-23T03:26:47.708-0500] {processor.py:186} INFO - Started process (PID=88269) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:26:47.716-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:26:47.719-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:26:47.718-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:26:47.723-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:26:47.723-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:26:47.724-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:26:47.724-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:26:47.724-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:26:47.737-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2025-02-23T03:27:45.043-0500] {processor.py:186} INFO - Started process (PID=88455) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:27:45.045-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:27:45.048-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:27:45.047-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:27:45.052-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:27:45.052-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:27:45.053-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:27:45.053-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:27:45.053-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:27:45.066-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-02-23T03:28:46.759-0500] {processor.py:186} INFO - Started process (PID=88645) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:28:46.761-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:28:46.766-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:28:46.765-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:28:46.772-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:28:46.771-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:28:46.773-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:28:46.772-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:28:46.773-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:28:46.790-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2025-02-23T03:29:48.183-0500] {processor.py:186} INFO - Started process (PID=88852) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:29:48.184-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:29:48.188-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:29:48.187-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:29:48.193-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:29:48.192-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:29:48.193-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:29:48.193-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:29:48.194-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:29:48.209-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-02-23T03:30:58.964-0500] {processor.py:186} INFO - Started process (PID=89126) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:30:58.970-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:30:58.973-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:30:58.973-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:30:58.977-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:30:58.977-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:30:58.978-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:30:58.978-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:30:58.978-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:30:58.991-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-02-23T03:32:02.926-0500] {processor.py:186} INFO - Started process (PID=89379) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:32:02.929-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:32:02.942-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:32:02.941-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:32:02.966-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:32:02.953-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:32:02.967-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:32:02.967-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:32:02.968-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:32:03.035-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.134 seconds
[2025-02-23T03:33:08.350-0500] {processor.py:186} INFO - Started process (PID=89602) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:33:08.352-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:33:08.356-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:33:08.355-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:33:08.362-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:33:08.361-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:33:08.362-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:33:08.362-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:33:08.363-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:33:08.379-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2025-02-23T03:34:17.299-0500] {processor.py:186} INFO - Started process (PID=89808) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:34:17.306-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:34:17.309-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:34:17.309-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:34:17.314-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:34:17.314-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:34:17.315-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:34:17.314-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:34:17.315-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:34:17.329-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2025-02-23T03:35:25.253-0500] {processor.py:186} INFO - Started process (PID=90045) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:35:25.255-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:35:25.259-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:35:25.258-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:35:25.264-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:35:25.264-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:35:25.265-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:35:25.265-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:35:25.266-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:35:25.281-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-02-23T03:36:29.445-0500] {processor.py:186} INFO - Started process (PID=90281) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:36:29.451-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:36:29.454-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:36:29.454-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:36:29.458-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:36:29.458-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:36:29.459-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:36:29.459-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:36:29.459-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:36:29.473-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-02-23T03:37:45.361-0500] {processor.py:186} INFO - Started process (PID=90503) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:37:45.368-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:37:45.371-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:37:45.370-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:37:45.375-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:37:45.374-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:37:45.375-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:37:45.375-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:37:45.376-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:37:45.388-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2025-02-23T03:38:51.116-0500] {processor.py:186} INFO - Started process (PID=90702) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:38:51.122-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:38:51.125-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:38:51.125-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:38:51.130-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:38:51.129-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:38:51.130-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:38:51.130-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:38:51.130-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:38:51.143-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-02-23T03:39:56.025-0500] {processor.py:186} INFO - Started process (PID=90918) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:39:56.031-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:39:56.042-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:39:56.042-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:39:56.058-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:39:56.057-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:39:56.059-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:39:56.059-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:39:56.060-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:39:56.114-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.113 seconds
[2025-02-23T03:41:05.550-0500] {processor.py:186} INFO - Started process (PID=91139) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:41:05.557-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:41:05.561-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:41:05.560-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:41:05.566-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:41:05.565-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:41:05.567-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:41:05.566-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:41:05.567-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:41:05.587-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2025-02-23T03:42:09.816-0500] {processor.py:186} INFO - Started process (PID=91384) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:42:09.818-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:42:09.821-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:42:09.820-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:42:09.825-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:42:09.824-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:42:09.825-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:42:09.825-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:42:09.826-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:42:09.838-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-02-23T03:43:14.095-0500] {processor.py:186} INFO - Started process (PID=91583) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:43:14.096-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:43:14.100-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:43:14.100-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:43:14.104-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:43:14.104-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:43:14.105-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:43:14.105-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:43:14.105-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:43:14.120-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2025-02-23T03:44:19.871-0500] {processor.py:186} INFO - Started process (PID=91774) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:44:19.873-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:44:19.876-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:44:19.875-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:44:19.881-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:44:19.880-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:44:19.881-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:44:19.881-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:44:19.882-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:44:19.895-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-02-23T03:45:36.579-0500] {processor.py:186} INFO - Started process (PID=92002) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:45:36.586-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:45:36.590-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:45:36.589-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:45:36.594-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:45:36.594-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:45:36.595-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:45:36.594-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:45:36.595-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:45:36.608-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-02-23T03:46:40.776-0500] {processor.py:186} INFO - Started process (PID=92223) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:46:40.778-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:46:40.781-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:46:40.780-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:46:40.785-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:46:40.784-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:46:40.785-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:46:40.785-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:46:40.786-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:46:40.802-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2025-02-23T03:47:42.536-0500] {processor.py:186} INFO - Started process (PID=92413) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:47:42.538-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:47:42.541-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:47:42.541-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:47:42.546-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:47:42.545-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:47:42.546-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:47:42.546-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:47:42.546-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:47:42.570-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2025-02-23T03:48:44.920-0500] {processor.py:186} INFO - Started process (PID=92602) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:48:44.923-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:48:44.927-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:48:44.926-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:48:44.936-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:48:44.935-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:48:44.937-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:48:44.936-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:48:44.937-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:48:44.955-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2025-02-23T03:49:45.050-0500] {processor.py:186} INFO - Started process (PID=92789) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:49:45.052-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:49:45.055-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:49:45.055-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:49:45.060-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:49:45.059-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:49:45.060-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:49:45.060-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:49:45.061-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:49:45.075-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2025-02-23T03:50:48.758-0500] {processor.py:186} INFO - Started process (PID=92982) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:50:48.760-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:50:48.763-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:50:48.763-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:50:48.768-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:50:48.767-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:50:48.769-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:50:48.769-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:50:48.770-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:50:48.784-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-02-23T03:52:01.805-0500] {processor.py:186} INFO - Started process (PID=93229) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:52:01.808-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:52:01.812-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:52:01.811-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:52:01.817-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:52:01.816-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:52:01.818-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:52:01.817-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:52:01.818-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:52:01.837-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2025-02-23T03:53:13.738-0500] {processor.py:186} INFO - Started process (PID=93445) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:53:13.740-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:53:13.743-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:53:13.742-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:53:13.747-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:53:13.746-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:53:13.747-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:53:13.747-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:53:13.748-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:53:13.761-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-02-23T03:54:18.035-0500] {processor.py:186} INFO - Started process (PID=93638) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:54:18.042-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:54:18.046-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:54:18.045-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:54:18.050-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:54:18.050-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:54:18.051-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:54:18.051-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:54:18.051-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:54:18.066-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2025-02-23T03:55:22.127-0500] {processor.py:186} INFO - Started process (PID=93836) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:55:22.129-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-23T03:55:22.131-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:55:22.131-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:55:22.136-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:55:22.135-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-23T03:55:22.136-0500] {logging_mixin.py:190} INFO - [2025-02-23T03:55:22.136-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-23T03:55:22.137-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-23T03:55:22.150-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
