[2025-02-22T23:43:55.372-0500] {processor.py:186} INFO - Started process (PID=26817) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:43:55.373-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-22T23:43:55.377-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:43:55.377-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:43:55.395-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:43:55.389-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:43:55.396-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:43:55.440-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.079 seconds
[2025-02-22T23:48:33.583-0500] {processor.py:186} INFO - Started process (PID=27419) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:48:33.591-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-22T23:48:33.596-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:48:33.595-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:48:33.634-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:48:33.615-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:48:33.635-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:48:33.699-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.142 seconds
[2025-02-22T23:49:41.205-0500] {processor.py:186} INFO - Started process (PID=27920) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:49:41.207-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-22T23:49:41.210-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:49:41.209-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:49:41.221-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:49:41.219-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:49:41.221-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:49:41.252-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.056 seconds
[2025-02-22T23:50:39.746-0500] {processor.py:186} INFO - Started process (PID=28364) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:50:39.750-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-22T23:50:39.753-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:50:39.753-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:50:39.774-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:50:39.766-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:50:39.775-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:50:39.808-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.074 seconds
[2025-02-22T23:51:38.069-0500] {processor.py:186} INFO - Started process (PID=28736) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:51:38.071-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-22T23:51:38.074-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:51:38.073-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:51:38.087-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:51:38.085-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:51:38.087-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:51:38.119-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.058 seconds
[2025-02-22T23:52:38.107-0500] {processor.py:186} INFO - Started process (PID=29196) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:52:38.109-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-22T23:52:38.111-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:52:38.111-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:52:38.126-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:52:38.121-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:52:38.126-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:52:38.164-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.068 seconds
[2025-02-22T23:54:10.910-0500] {processor.py:186} INFO - Started process (PID=29846) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:54:10.915-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-22T23:54:10.921-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:54:10.920-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:54:10.950-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:54:10.938-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:54:10.951-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:54:11.020-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.125 seconds
[2025-02-22T23:55:14.547-0500] {processor.py:186} INFO - Started process (PID=30276) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:55:14.550-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-22T23:55:14.553-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:55:14.553-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:55:14.586-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:55:14.573-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:55:14.587-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:55:14.652-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.119 seconds
[2025-02-22T23:58:25.756-0500] {processor.py:186} INFO - Started process (PID=30750) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:58:25.764-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-22T23:58:25.767-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:58:25.766-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:58:25.780-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:58:25.778-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:58:25.781-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:58:25.824-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.076 seconds
[2025-02-22T23:59:31.223-0500] {processor.py:186} INFO - Started process (PID=31249) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:59:31.226-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-22T23:59:31.229-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:59:31.228-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:59:31.248-0500] {logging_mixin.py:190} INFO - [2025-02-22T23:59:31.239-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-22T23:59:31.249-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-22T23:59:31.287-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.074 seconds
[2025-02-23T00:00:54.279-0500] {processor.py:186} INFO - Started process (PID=31754) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:00:54.281-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T00:00:54.284-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:00:54.284-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:00:54.297-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:00:54.295-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:00:54.297-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:00:54.328-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.057 seconds
[2025-02-23T00:01:55.798-0500] {processor.py:186} INFO - Started process (PID=32183) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:01:55.800-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T00:01:55.803-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:01:55.802-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:01:55.813-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:01:55.811-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:01:55.813-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:01:55.840-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.051 seconds
[2025-02-23T00:11:34.614-0500] {processor.py:186} INFO - Started process (PID=34452) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:11:34.621-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T00:11:34.625-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:11:34.624-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:11:34.644-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:11:34.637-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:11:34.645-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:11:34.690-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.084 seconds
[2025-02-23T00:12:48.789-0500] {processor.py:186} INFO - Started process (PID=34568) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:12:48.791-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T00:12:48.794-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:12:48.794-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:12:48.804-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:12:48.802-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:12:48.805-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:12:48.831-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.050 seconds
[2025-02-23T00:13:47.425-0500] {processor.py:186} INFO - Started process (PID=34635) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:13:47.431-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T00:13:47.435-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:13:47.434-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:13:47.444-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:13:47.442-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:13:47.444-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:13:47.474-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.058 seconds
[2025-02-23T00:14:45.788-0500] {processor.py:186} INFO - Started process (PID=34710) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:14:45.790-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T00:14:45.793-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:14:45.792-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:14:45.802-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:14:45.801-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:14:45.803-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:14:45.834-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.054 seconds
[2025-02-23T00:15:55.321-0500] {processor.py:186} INFO - Started process (PID=34835) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:15:55.323-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T00:15:55.326-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:15:55.325-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:15:55.336-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:15:55.334-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:15:55.336-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:15:55.367-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.054 seconds
[2025-02-23T00:17:00.268-0500] {processor.py:186} INFO - Started process (PID=34907) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:17:00.269-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T00:17:00.272-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:17:00.272-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:17:00.282-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:17:00.280-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:17:00.282-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:17:00.313-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.054 seconds
[2025-02-23T00:18:00.712-0500] {processor.py:186} INFO - Started process (PID=34985) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:18:00.720-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T00:18:00.724-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:18:00.723-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:18:00.734-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:18:00.732-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:18:00.734-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:18:00.770-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.067 seconds
[2025-02-23T00:22:14.346-0500] {processor.py:186} INFO - Started process (PID=35199) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:22:14.348-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T00:22:14.350-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:22:14.350-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:22:14.360-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:22:14.358-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:22:14.360-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:22:14.390-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.053 seconds
[2025-02-23T00:23:19.291-0500] {processor.py:186} INFO - Started process (PID=35266) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:23:19.299-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T00:23:19.302-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:23:19.302-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:23:19.315-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:23:19.312-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:23:19.315-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:23:19.348-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.065 seconds
[2025-02-23T00:24:22.330-0500] {processor.py:186} INFO - Started process (PID=35344) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:24:22.337-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T00:24:22.341-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:24:22.340-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:24:22.351-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:24:22.349-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:24:22.352-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:24:22.384-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.065 seconds
[2025-02-23T00:25:21.780-0500] {processor.py:186} INFO - Started process (PID=35410) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:25:21.786-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T00:25:21.789-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:25:21.788-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:25:21.798-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:25:21.797-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:25:21.799-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:25:21.830-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.059 seconds
[2025-02-23T00:26:21.020-0500] {processor.py:186} INFO - Started process (PID=35486) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:26:21.022-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T00:26:21.025-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:26:21.024-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:26:21.035-0500] {logging_mixin.py:190} INFO - [2025-02-23T00:26:21.033-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T00:26:21.035-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T00:26:21.076-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.065 seconds
[2025-02-23T02:31:50.295-0500] {processor.py:186} INFO - Started process (PID=76060) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:31:50.303-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T02:31:50.305-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:31:50.305-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:31:50.315-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:31:50.313-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:31:50.316-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:31:50.349-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.063 seconds
[2025-02-23T02:32:52.710-0500] {processor.py:186} INFO - Started process (PID=76462) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:32:52.713-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T02:32:52.716-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:32:52.715-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:32:52.725-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:32:52.723-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:32:52.725-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:32:52.761-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.059 seconds
[2025-02-23T02:34:07.540-0500] {processor.py:186} INFO - Started process (PID=76868) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:34:07.547-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T02:34:07.550-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:34:07.549-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:34:07.559-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:34:07.558-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:34:07.560-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:34:07.594-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.064 seconds
[2025-02-23T02:35:34.133-0500] {processor.py:186} INFO - Started process (PID=77210) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:35:34.135-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T02:35:34.139-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:35:34.138-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:35:34.153-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:35:34.150-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:35:34.154-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:35:34.208-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.086 seconds
[2025-02-23T02:43:18.619-0500] {processor.py:186} INFO - Started process (PID=79066) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:43:18.620-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T02:43:18.624-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:43:18.623-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:43:18.634-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:43:18.632-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:43:18.634-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:43:18.664-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.054 seconds
[2025-02-23T02:44:17.610-0500] {processor.py:186} INFO - Started process (PID=79268) to work on /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:44:17.616-0500] {processor.py:914} INFO - Processing file /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py for tasks to queue
[2025-02-23T02:44:17.619-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:44:17.618-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:44:17.630-0500] {logging_mixin.py:190} INFO - [2025-02-23T02:44:17.627-0500] {dagbag.py:387} ERROR - Failed to import: /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
Traceback (most recent call last):
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 64, in <module>
    example_dag = example_sla_dag()
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py", line 52, in example_sla_dag
    def sleep_20():
  File "/home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 691, in decorator_factory
    return _TaskDecorator(
TypeError: _TaskDecorator() takes no arguments
[2025-02-23T02:44:17.630-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py
[2025-02-23T02:44:17.658-0500] {processor.py:208} INFO - Processing /home/rafaelrb/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_sla_dag.py took 0.057 seconds
